version: '2.1'

services:
  mysql:
    container_name: mysql
    image: mysql
    build: ./DB
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: Conseil_voyage
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
  app:
    container_name: app
    image: app
    depends_on:
     - "mysql"
    links:
      - mysql:mysql
    build: ./App
    ports:
      - 49160:8080
    volumes:
      - "./App:/usr/src/app"
